/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MYPC
 */
public class CardPayment extends javax.swing.JFrame {

    /**
     * Creates new form CardPayment
     */
    public CardPayment() {
        initComponents();
    }
    
    String username="";
    int bookingID=0;
    
    public CardPayment(String usname,int bID) {
        initComponents();
        bookingID=bID;
        username=usname;
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt0=con.createStatement();
            
            ResultSet rs=stmt.executeQuery("select * from USERDASHBOARD");
            
            
            while(rs.next())
            {
                if(Integer.parseInt(rs.getString("BOOKING_ID"))==bookingID)
                {
                    amtText.setText(rs.getString("AMOUNT"));
                    break;
                }
            }
            
            ResultSet rs0=stmt0.executeQuery("select * from CardDetails");
            int flag=0;
            while(rs0.next())
            {
                if(rs0.getString("username").equals(username))
                {
                    flag=1;
                    cardnumberText.setText(rs0.getString("cardnumber"));
                    cvvText.setText(rs0.getString("cvvNumber"));
                    expText.setText(rs0.getString("expDate"));
                    nameText.setText(rs0.getString("nameoncard"));
                    break;
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amtText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cardnumberText = new javax.swing.JTextField();
        cvvText = new javax.swing.JTextField();
        expText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Card Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 58));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Amount to be Paid:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 109, 151, 58));

        amtText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amtText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(amtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, 85, 58));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Card Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 202, 109, 46));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CVV:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 278, 109, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Expiry Year:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 336, 109, 39));

        cardnumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(cardnumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 215, 133, -1));
        getContentPane().add(cvvText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 283, 133, -1));
        getContentPane().add(expText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 353, 133, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name As On Card");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 206, -1, 39));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 183, 44));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Pay Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 401, -1, 41));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\debit_cards_prepaid_cards.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cardnumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnumberTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            
            ResultSet rs=stmt.executeQuery("select * from CardDetails");
            int flag=0;
            while(rs.next())
            {
                if(rs.getString("username").equals(username))
                {
                    flag=1;
                    break;
                }
            }
            if(flag==0)
            {
                String cardNo=cardnumberText.getText();
                String cvv=cvvText.getText();
                String exp=expText.getText();
                String name=nameText.getText();
                
                stmt1.executeUpdate("Insert into CardDetails values('"+username+"','"+cardNo+"','"+cvv+"','"+exp+"','"+name+"')");
                JOptionPane.showMessageDialog(this, "Payment Succesfull!!");
                this.dispose();
                Login_Activity s= new Login_Activity();
                s.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Payment Succesfull!!");
                this.dispose();
                Login_Activity s= new Login_Activity();
                s.setVisible(true);
            }
            /*else
            {
                cardnumberText.setText(rs.getString("cardnumber"));
                cvvText.setText(rs.getString("cvvNumber"));
                expText.setText(rs.getString("expDate"));
                nameText.setText(rs.getString("nameoncard"));
                JOptionPane.showMessageDialog(this, "Payment Succesfull!!");
            }*/
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtText;
    private javax.swing.JTextField cardnumberText;
    private javax.swing.JTextField cvvText;
    private javax.swing.JTextField expText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameText;
    // End of variables declaration//GEN-END:variables
}
