/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class DriverCreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form DriverCreateAccount
     */
    public DriverCreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullnameText = new javax.swing.JTextField();
        licenseText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dobText = new javax.swing.JTextField();
        mobNoText = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Create Account (Driver)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 11, -1, 112));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Date of Birth: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 358, -1, 51));
        getContentPane().add(fullnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 146, 42));
        getContentPane().add(licenseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 179, 146, 42));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 118, 51));

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 146, 42));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Full Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 118, 51));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("License No:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 172, 128, 51));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Mob No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 266, 128, 51));

        dobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextActionPerformed(evt);
            }
        });
        getContentPane().add(dobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 365, 146, 42));

        mobNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobNoTextActionPerformed(evt);
            }
        });
        getContentPane().add(mobNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 273, 146, 42));

        createBtn.setBackground(new java.awt.Color(255, 255, 0));
        createBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createBtn.setText("Continue");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 501, 174, 66));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 119, 56));

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 143, 55));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\confitm.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobNoTextActionPerformed

    public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            Statement stmt0=con.createStatement();
            System.out.println("Hello");
            //String driverid=driverIDText.getText();
            String usrname = usernameText.getText();
            String fullname = fullnameText.getText();
            String license = licenseText.getText();
            String mobNo = mobNoText.getText();
            String dob = dobText.getText();
            String pass= passwordText.getText();
            System.out.println("Hello");
            
            ResultSet rs0=stmt0.executeQuery("select * from driver order by DRIVER_ID");
            int did=0;
            while(rs0.next())
            {
                did=Integer.parseInt(rs0.getString("DRIVER_ID"));
            }
            int driverid=did+1;
            System.out.println("Driver ID: "+driverid);
            ResultSet rs=stmt.executeQuery("select * from driver");
            int flag=0;
            while (rs.next()){
                String checkuser=rs.getString("user_name");
                if(checkuser.equals(usrname))
                {
                    flag=1;
                    JOptionPane.showMessageDialog(this, "Account Exist!!");
                    break;
                }
            }
            System.out.println("Hello +flag: "+flag);
            if(flag==0)
            {
                stmt1.executeUpdate("insert into driver values('"+driverid+"','"+fullname+"','"+usrname+"','"+pass+"','"+license+"','"+mobNo+"','"+dob+"')");
                System.out.println("insert into driver values('"+driverid+"','"+fullname+"','"+usrname+"','"+pass+"','"+license+"','"+mobNo+"','"+dob+"')");
                stmt2.executeUpdate("insert into login values('Driver','"+usrname+"','"+pass+"')");
                System.out.println("insert into login values('Driver','"+usrname+"','"+pass+"')");
                JOptionPane.showMessageDialog(this, "Account Created Successfully!!");
                //close();
                this.dispose();
                VehicleDetailsActivity s2= new VehicleDetailsActivity(driverid);
                s2.setVisible(true);
            }
            
            con.close();
        } catch (Exception e) {
            e.toString();
        }
        
        
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void dobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverCreateAccount().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField dobText;
    private javax.swing.JTextField fullnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField licenseText;
    private javax.swing.JTextField mobNoText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
