/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class DriverLocationActivity extends javax.swing.JFrame {

    /**
     * Creates new form DriverLocationActivity
     */
    String username;
    public DriverLocationActivity() {
        initComponents();
    }
    public DriverLocationActivity(String username1) {
        
        initComponents();
        
        username=username1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        locationText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Driver Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 40, 247, 82));

        locationText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        locationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextActionPerformed(evt);
            }
        });
        getContentPane().add(locationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 282, 74));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Your Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 221, 74));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 181, 54));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 387, 185, 54));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\location.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Hello");
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            
            String driverlocation=locationText.getText();
            System.out.println("Hello");
            if(driverlocation.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please Enter Your Location First!!");
            }
            else
            {
                ResultSet rs=stmt.executeQuery("select * from driver");
                String driverid="";
                while (rs.next()) {                    
                    driverid=rs.getString("DRIVER_ID");
                    String usname=rs.getString("USER_NAME");
                    
                    if(usname.equals(username))
                    {
                        break;
                    }
                }
                
                ResultSet rs0=stmt.executeQuery("select * from driver_location");
                int flag0=0;
                
                while(rs0.next())
                {
                    if(rs0.getString("DRIVER_ID").equals(driverid))
                    {
                        flag0=1;
                        break;
                    }
                }
                
                if(flag0==1)
                {
                    System.out.println("username: "+username);
                    System.out.println("driverid: "+driverid);
                    ResultSet rs1=stmt.executeQuery("select * from vehicle_details ");
                    String vehicleType="";

                    while (rs1.next()) {

                        vehicleType=rs1.getString("VEHICLE_TYPE");
                        String id=rs1.getString("DRIVER_ID");

                        if(id.equals(driverid))
                        {
                            break;
                        }
                    }
                    System.out.println("VEHICLE_TYPE: "+vehicleType);
                    stmt1.executeUpdate("Update DRIVER_LOCATION SET DRIVER_LOCATION='"+driverlocation+"' where DRIVER_ID='"+driverid+"'");
                    JOptionPane.showMessageDialog(this, "Looking For Customers...");
                    //close();
                    DriverConfirmationActivity s = new DriverConfirmationActivity(driverid,driverlocation,vehicleType);
                    s.setVisible(true);
                }
                else
                {
                    System.out.println("username: "+username);
                    System.out.println("driverid: "+driverid);
                    ResultSet rs1=stmt.executeQuery("select * from vehicle_details ");
                    String vehicleType="";

                    while (rs1.next()) {

                        vehicleType=rs1.getString("VEHICLE_TYPE");
                        String id=rs1.getString("DRIVER_ID");

                        if(id.equals(driverid))
                        {
                            break;
                        }
                    }
                    System.out.println("VEHICLE_TYPE: "+vehicleType);
                    stmt1.executeUpdate("Insert into DRIVER_LOCATION values('"+driverid +"','"+vehicleType+"','"+driverlocation +"')");
                    JOptionPane.showMessageDialog(this, "Looking For Customers...");
                    //close();
                    this.dispose();
                    DriverConfirmationActivity s = new DriverConfirmationActivity(driverid,driverlocation,vehicleType);
                    s.setVisible(true);
                }
            }
            con.close();
        } catch (Exception e) {
            e.toString();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void locationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverLocationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverLocationActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField locationText;
    // End of variables declaration//GEN-END:variables
}
