/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MYPC
 */
public class DriverConfirmationActivity extends javax.swing.JFrame {

    /**
     * Creates new form DriverConfirmationActivity
     */
    public DriverConfirmationActivity() {
        initComponents();
    }
    String driverId="";
    String driverlocation="";
    String vehicleType="";
    String bookid="";
    public DriverConfirmationActivity(String driveid,String drivelocation,String vehtype) {
        initComponents();
        driverId=driveid;
        driverlocation=drivelocation;
        vehicleType=vehtype;
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); 
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            String drop="";
            
            ResultSet rs=stmt.executeQuery("select * from USERDASHBOARD");
            String usname="";
            int temp=0;
            String[] dropLocation= new String[10];
            while(rs.next())
            {
                if(rs.getString("BOARDING_PT").equals(driverlocation)&&rs.getString("VEHICLE_TYPE").equals(vehicleType))
                {
                    usname=rs.getString("USERNAME");
                    drop=rs.getString("DROPPING_PT");
                    dropLocation[temp]=drop;
                    selectMenu.addItem(drop);
                    temp++;
                }
            }
            
            
            
            
            
        } catch (Exception e) {
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        custnameText = new javax.swing.JLabel();
        mobText = new javax.swing.JLabel();
        pickText = new javax.swing.JLabel();
        dropText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selectMenu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 31, 230, 53));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 117, 137, 52));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mobile No:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 187, 137, 58));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pickup Location:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 263, 137, 54));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dropping Location:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 54));

        custnameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(custnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 117, 147, 42));

        mobText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(mobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 187, 147, 58));

        pickText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(pickText, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 267, 150, 50));

        dropText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dropText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 136, 54));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 393, 148, 52));

        selectMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMenuActionPerformed(evt);
            }
        });
        getContentPane().add(selectMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 119, 111, 33));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\yeesh\\Downloads\\sand.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMenuActionPerformed
        // TODO add your handling code here:
        
        String selectedLoc=selectMenu.getSelectedItem().toString();
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); 
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            
            ResultSet rs=stmt.executeQuery("select * from USERDASHBOARD");
            
            String usname="";
            int temp=0;
            String[] dropLocation= new String[10];
            String drop="";
            
            while(rs.next())
            {
                if(rs.getString("DROPPING_PT").equals(selectedLoc))
                {
                    usname=rs.getString("USERNAME");
                    drop=rs.getString("DROPPING_PT");
                    bookid=rs.getString("BOOKING_ID");
                    break;
                }
            }
            
            ResultSet rs1=stmt1.executeQuery("select * from users");
            
            String name="";
            String mobno="";
            
            while(rs1.next())
            {
                if(rs1.getString("USER_NAME").equals(usname))
                {
                    name=rs1.getString("FULL_NAME");
                    mobno=rs1.getString("MOB_NO");
                    break;
                }
            }
            
            custnameText.setText(name);
            mobText.setText(mobno);
            pickText.setText(driverlocation);
            dropText.setText(drop);
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_selectMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); 
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            
            String custname=custnameText.getText();
            String mob=mobText.getText();
            String pick=pickText.getText();
            String dropp=dropText.getText();
            String amt="";
            ResultSet rs=stmt.executeQuery("select * from USERDASHBOARD");
            
            while(rs.next())
            {
                if(rs.getString("BOOKING_ID").equals(bookid))
                {
                    amt=rs.getString("AMOUNT");
                    break;
                }
            }
            this.dispose();
            DriverPaymentActivity s = new DriverPaymentActivity(amt);
            s.setVisible(true);
            
            
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverConfirmationActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custnameText;
    private javax.swing.JLabel dropText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mobText;
    private javax.swing.JLabel pickText;
    private javax.swing.JComboBox<String> selectMenu;
    // End of variables declaration//GEN-END:variables
}
