/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Login_Activity extends javax.swing.JFrame {

    /**
     * Creates new form Login_Activity
     */
    public Login_Activity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        customerRadioBtn = new javax.swing.JRadioButton();
        driverRadioBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        creatAccountBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Cab Ride Booking System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 51, -1, 60));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 233, -1, 38));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 306, 90, 38));

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 234, 223, 38));
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 307, 223, 38));

        loginBtn.setBackground(new java.awt.Color(255, 204, 204));
        loginBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 51, 51));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 170, 50));

        customerRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(customerRadioBtn);
        customerRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        customerRadioBtn.setText("Customer");
        customerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRadioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 165, 115, -1));

        driverRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(driverRadioBtn);
        driverRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        driverRadioBtn.setText("Driver");
        driverRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverRadioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(driverRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 165, 111, -1));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("User Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 158, 121, 45));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 33, -1, -1));

        creatAccountBtn.setBackground(new java.awt.Color(255, 204, 204));
        creatAccountBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        creatAccountBtn.setText("Create Account");
        creatAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatAccountBtnActionPerformed(evt);
            }
        });
        getContentPane().add(creatAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 167, 50));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 170, 60));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\car2.png")); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 780, 560));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void customerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerRadioBtnActionPerformed

    private void driverRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverRadioBtnActionPerformed

    public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); 
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            
            String usrname=usernameText.getText();
            String pass=passwordText.getText();
            
            System.out.println("Username: "+usrname+" Pass: "+pass);
            
            if(!customerRadioBtn.isSelected()&&!driverRadioBtn.isSelected())
            {
                JOptionPane.showMessageDialog(this, "Please Select User Type!!");
            }
            else if(customerRadioBtn.isSelected())
            {
                if(usrname.isEmpty()&&pass.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Username & Password!!!");
                }
                else if(usrname.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Username!!!");
                }
                else if(pass.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Password!!!");
                }
                else{
                    ResultSet rs=stmt.executeQuery("select * from login");
                    System.out.println("Below select *");
                    int flag=0;
                    while (rs.next()) {
                        
                        String usname=rs.getString("USER_NAME");
                        String pss=rs.getString("PASSWORD");
                        String type=rs.getString("USER_TYPE");
                        
                        if(usname.equals(usrname)&&pss.equals(pass)&&type.equals("Customer"))
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this, "LOGIN SUCCESSFULL!!");
                            //close();
                            this.dispose();
                            UserDashboardActivity sk=new UserDashboardActivity(usname);
                            sk.setVisible(true);
                            break;
                        }
                        else if(usname.equals(usrname)&&!pss.equals(pass))
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this, "Password Incorrect!!");
                            break;
                        }
                    }
                    if(flag==0)
                    {
                        JOptionPane.showMessageDialog(this, "No Account!!");
                    }
                    
                }
                con.close();
            }
            else{
                if(usrname.isEmpty()&&pass.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Username & Password!!!");
                }
                else if(usrname.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Username!!!");
                }
                else if(pass.isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Please Enter Password!!!");
                }
                else{
                    ResultSet rs=stmt1.executeQuery("select * from login");
                    int flag=0;
                    while (rs.next()) {
                        String usname=rs.getString("USER_NAME");
                        String pss=rs.getString("password");
                        String type=rs.getString("USER_TYPE");
                        if(usname.equals(usrname)&&pss.equals(pass)&&type.equals("Driver"))
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this, "LOGIN SUCCESSFULL!!");
                            //close();
                            this.dispose();
                            DriverLocationActivity s=new DriverLocationActivity(usname);
                            s.setVisible(true);
                            break;
                        }
                        else if(usname.equals(usrname)&&!pss.equals(pass))
                        {
                            flag=1;
                            JOptionPane.showMessageDialog(this, "Password Incorrect!!");
                        }
                    }
                    if(flag==0)
                    {
                        JOptionPane.showMessageDialog(this, "No Account!!");
                    }
                }
                con.close();
            }
        } catch (Exception e) {
            e.toString();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void creatAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatAccountBtnActionPerformed
        // TODO add your handling code here:
        Login_Activity s3=new Login_Activity();
        if(customerRadioBtn.isSelected())
        {
            close();
            CreateAccountActivity s =new CreateAccountActivity();
            s.setVisible(true);
        }
        else if(driverRadioBtn.isSelected())
        {
            close();
            DriverCreateAccount s1= new DriverCreateAccount();
            s1.setVisible(true);
        }
    }//GEN-LAST:event_creatAccountBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton creatAccountBtn;
    private javax.swing.JRadioButton customerRadioBtn;
    private javax.swing.JRadioButton driverRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
