/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author MYPC
 */
public class UserConfirmationActivity extends javax.swing.JFrame {

    /**
     * Creates new form UserConfirmationActivity
     */
    public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    public UserConfirmationActivity() {
        initComponents();
    }
    String dpt="";
    String usname="";
    int bookingID=0;
    public UserConfirmationActivity(String boardingPoint,String vehicleType,String dropPt,String username,int bID) {
        initComponents();
        dpt=dropPt;
        usname=username;
        bookingID=bID;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            Statement stmt0=con.createStatement();
            
            ResultSet rs=stmt.executeQuery("select * from driver_location");
            
            String id="";
            int temp=0;
            int flag=0;
            while (rs.next()) {                
                
                String location=rs.getString("DRIVER_LOCATION");
                String vehiType=rs.getString("VEHICLE_TYPE");
                
                
                if(location.equals(boardingPoint)&&vehiType.equals(vehicleType))
                {
                    temp=1;
                    id=rs.getString("DRIVER_ID");
                    /*ResultSet rs0=stmt0.executeQuery("select * from vehicle_details;");
                    
                    while(rs0.next())
                    {
                        if(rs0.getString("DRIVER_ID").equals(id))
                        {
                            selectMenu.addItem(rs0.getString("VEHICLE_NAME"));
                        }
                    }*/
                    
                    flag++;
                    break;
                }
            }
            
            if(temp==0)
            {
                JOptionPane.showMessageDialog(this, "SORRY! NO CAB AVAILABLE!");
                jButton1.setEnabled(false);
                close();
            }
            
            ResultSet rs1=stmt1.executeQuery("select * from driver");
            
            String name="";
            String mobno="";
            while (rs1.next()) {                
                
                if(rs1.getString("DRIVER_ID").equals(id))
                {
                    name=rs1.getString("DRIVER_NAME");
                    mobno=rs1.getString("DRIVER_MOB_NO");
                    break;
                }
            }
            
            ResultSet rs2=stmt2.executeQuery("select * from vehicle_details");
            
            String vehName="";
            String cabno="";
            while (rs2.next()) {                
                if(rs2.getString("DRIVER_ID").equals(id))
                {
                    vehName=rs2.getString("VEHICLE_NAME");
                    cabno=rs2.getString("VEHICLE_REG_NO");
                }
            }
            dnameText2.setText(name);
            mobText.setText(mobno);
            vehnameText.setText(vehName);
            cabText.setText(cabno);
            
            
            con.close();
        } catch (Exception e) {
            e.toString();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mobText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cabText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dnameText2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehnameText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 260, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driver Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 115, 205, 59));

        mobText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(mobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 278, 165, 59));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vehicle Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 146, 59));

        cabText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cabText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cabText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 165, 59));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Driver Mob No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 278, 205, 59));

        dnameText2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dnameText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dnameText2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(dnameText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 165, 59));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cab No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 146, 59));

        vehnameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehnameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehnameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(vehnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 165, 59));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 135, 59));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\clock.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            Statement stmt3=con.createStatement();
            
            String dname=dnameText2.getText();
            
            ResultSet rs=stmt.executeQuery("select * from driver");
            String id="";
            
            while(rs.next())
            {
                if(rs.getString("DRIVER_NAME").equals(dname))
                {
                    id=rs.getString("DRIVER_ID");
                    break;
                }
            }
            ResultSet rs1=stmt1.executeQuery("select * from driver_location");
            
            stmt3.executeUpdate("Update driver_location SET DRIVER_LOCATION='"+dpt+"' where DRIVER_ID='"+id+"'");
            JOptionPane.showMessageDialog(this, "Order Successfull!!");
            this.dispose();
            PaymentOption sk=new PaymentOption(usname,bookingID);
            sk.setVisible(true);
            
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConfirmationActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserConfirmationActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cabText;
    private javax.swing.JLabel dnameText2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel mobText;
    private javax.swing.JLabel vehnameText;
    // End of variables declaration//GEN-END:variables
}
