/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package1;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class VehicleDetailsActivity extends javax.swing.JFrame {

    /**
     * Creates new form VehicleDetailsActivity
     */
    public VehicleDetailsActivity() {
        initComponents();
    }
    int driverid=0;
     public VehicleDetailsActivity(int did) {
        initComponents();
        driverid=did;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vehicleNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        suvCarRadiobtn = new javax.swing.JRadioButton();
        miniCarRadiobtn = new javax.swing.JRadioButton();
        microCarRadiobtn = new javax.swing.JRadioButton();
        sedanCarRadiobtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        vehicleRegYearText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vehicleRegNoText = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Vehicle Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 243, 79));

        vehicleNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNameTextActionPerformed(evt);
            }
        });
        getContentPane().add(vehicleNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 200, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Vehicle Name: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, 61));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Vehicle Type: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 61));

        suvCarRadiobtn.setBackground(new java.awt.Color(204, 204, 255));
        suvCarRadiobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        suvCarRadiobtn.setText("SUV Car");
        suvCarRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suvCarRadiobtnActionPerformed(evt);
            }
        });
        getContentPane().add(suvCarRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 115, 40));

        miniCarRadiobtn.setBackground(new java.awt.Color(204, 204, 255));
        miniCarRadiobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        miniCarRadiobtn.setText("Mini Car");
        getContentPane().add(miniCarRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 115, 40));

        microCarRadiobtn.setBackground(new java.awt.Color(204, 204, 255));
        microCarRadiobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        microCarRadiobtn.setText("Micro Car");
        microCarRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                microCarRadiobtnActionPerformed(evt);
            }
        });
        getContentPane().add(microCarRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 115, 40));

        sedanCarRadiobtn.setBackground(new java.awt.Color(204, 204, 255));
        sedanCarRadiobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sedanCarRadiobtn.setText("Sedan Car");
        sedanCarRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedanCarRadiobtnActionPerformed(evt);
            }
        });
        getContentPane().add(sedanCarRadiobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 115, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Vehicle Reg Year: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 354, -1, 61));
        getContentPane().add(vehicleRegYearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 180, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Vehicle Reg No: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 71));

        vehicleRegNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleRegNoTextActionPerformed(evt);
            }
        });
        getContentPane().add(vehicleRegNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 180, 40));

        createBtn.setBackground(new java.awt.Color(255, 102, 102));
        createBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createBtn.setText("Create Account");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 465, 197, 62));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYPC\\Downloads\\green1.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void suvCarRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suvCarRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suvCarRadiobtnActionPerformed

    private void microCarRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_microCarRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_microCarRadiobtnActionPerformed

    private void sedanCarRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedanCarRadiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sedanCarRadiobtnActionPerformed

    private void vehicleRegNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleRegNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleRegNoTextActionPerformed

    public void close()
    {
        WindowEvent closeWindow= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); //Load the driver class
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","hr"); // Creating a connection object
            Statement stmt=con.createStatement();
            Statement stmt1=con.createStatement();
            Statement stmt2=con.createStatement();
            System.out.println("Vehicle");
            //String driveID=driverIDTEXT1.getText();
            String vehiclename= vehicleNameText.getText();
            String regNo=vehicleRegNoText.getText();
            String regYear=vehicleRegYearText.getText();
            String vehicletype="";
            System.out.println("Vehicle");
            if(!miniCarRadiobtn.isSelected()&&!microCarRadiobtn.isSelected()&&!sedanCarRadiobtn.isSelected()&&!suvCarRadiobtn.isSelected())
            {
                JOptionPane.showMessageDialog(this, "Please Select Vehicle Type!!");
            }
            else
            {
                if(miniCarRadiobtn.isSelected())
                {
                    vehicletype="Mini Car";
                }
                else if(microCarRadiobtn.isSelected())
                {
                    vehicletype="Micro Car";
                }
                else if(suvCarRadiobtn.isSelected())
                {
                    vehicletype="SUV Car";
                }
                else
                {
                    vehicletype="Sedan Car";
                }
                ResultSet rs=stmt.executeQuery("select * from driver");
                System.out.println("Vehicle");
                stmt.executeUpdate("Insert Into VEHICLE_DETAILS Values('"+driverid+"','"+vehicletype+"','"+vehiclename+"','"+regNo+"','"+regYear+"')");
                JOptionPane.showMessageDialog(this, "Vehicle Details Added Successfully!!");
                //close();
                this.dispose();
                Login_Activity s= new Login_Activity();
                s.setVisible(true);
            }
            
        } catch (Exception e) {
            e.toString();
        }
      
    }//GEN-LAST:event_createBtnActionPerformed

    private void vehicleNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleDetailsActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleDetailsActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleDetailsActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleDetailsActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleDetailsActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton microCarRadiobtn;
    private javax.swing.JRadioButton miniCarRadiobtn;
    private javax.swing.JRadioButton sedanCarRadiobtn;
    private javax.swing.JRadioButton suvCarRadiobtn;
    private javax.swing.JTextField vehicleNameText;
    private javax.swing.JTextField vehicleRegNoText;
    private javax.swing.JTextField vehicleRegYearText;
    // End of variables declaration//GEN-END:variables
}
